/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMonitor;

import DAO.impresoraDAO;
import VO.impresoraVO;
import DAO.MarcaDAO;
import Teclado.Teclado;


/**
 *
 * @author Sergio
 */
public class BuscarimpresoraiUI extends javax.swing.JPanel {

    private impresoraDAO Lasimpresoras;
    private MarcaDAO LasMarcas;
    private impresoraVO buscado;
    private Teclado pp = new Teclado();
    

    /**
     * Creates new form BuscarMoniUI
     */
    public BuscarimpresoraiUI(impresoraDAO local, MarcaDAO LasMarcas) {

        this.Lasimpresoras = local;
        this.LasMarcas = LasMarcas;
        initComponents();

        this.JT_ID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_TituloBuscaMoni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JT_BUScpu = new javax.swing.JTextField();
        JT_idBuscar = new javax.swing.JButton();
        JL_ID = new javax.swing.JLabel();
        JT_ID = new javax.swing.JTextField();
        JL_Serie = new javax.swing.JLabel();
        JT_Serie = new javax.swing.JTextField();
        JL_Marca = new javax.swing.JLabel();
        JL_TIpo = new javax.swing.JLabel();
        JT_Tipo = new javax.swing.JTextField();
        JB_ACTIVAR = new javax.swing.JButton();
        JB_REGCAMBIOS = new javax.swing.JButton();
        JB_CANCELAR = new javax.swing.JButton();
        JCB_marcaimpresora = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 51, 204));

        JL_TituloBuscaMoni.setBackground(new java.awt.Color(0, 255, 255));
        JL_TituloBuscaMoni.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        JL_TituloBuscaMoni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_TituloBuscaMoni.setText("Formulario para buscar impresora");

        jLabel1.setText("Buscar por ID");

        JT_idBuscar.setText("Buscar");
        JT_idBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_idBuscarActionPerformed(evt);
            }
        });

        JL_ID.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JL_ID.setText("ID");

        JL_Serie.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JL_Serie.setText("Serie");

        JT_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_SerieActionPerformed(evt);
            }
        });

        JL_Marca.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JL_Marca.setText("Marca");

        JL_TIpo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JL_TIpo.setText("Tipo");

        JT_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_TipoActionPerformed(evt);
            }
        });

        JB_ACTIVAR.setText("Activar");
        JB_ACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ACTIVARActionPerformed(evt);
            }
        });

        JB_REGCAMBIOS.setText("Registrar Cambios");
        JB_REGCAMBIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGCAMBIOSActionPerformed(evt);
            }
        });

        JB_CANCELAR.setText("Cancelar");

        JCB_marcaimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_marcaimpresoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_TIpo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JL_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JT_BUScpu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(JT_idBuscar))
                                    .addComponent(JT_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JT_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(JCB_marcaimpresora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JB_CANCELAR)
                                            .addComponent(JB_ACTIVAR)
                                            .addComponent(JB_REGCAMBIOS)))))
                            .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JL_TituloBuscaMoni)))
                        .addContainerGap(167, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JL_TituloBuscaMoni)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_BUScpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_idBuscar))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_ACTIVAR)
                        .addGap(18, 18, 18)
                        .addComponent(JB_REGCAMBIOS))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JCB_marcaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JL_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_TIpo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CANCELAR))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JT_idBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_idBuscarActionPerformed

        int ID = Integer.parseInt(this.JT_BUScpu.getText());
        buscado = this.Lasimpresoras.buscarXID(ID);
        if (buscado != null) {
            this.JT_ID.setText("" + buscado.getID());
            this.JT_ID.setVisible(true);
            this.JT_ID.setEditable(false);
            this.JT_Serie.setText(buscado.getSerie());
            this.JT_Tipo.setText(buscado.getTipo());
            
            Object marcas[] = this.LasMarcas.getBDMarca();
            
            this.JCB_marcaimpresora.removeAllItems();
            for (int i = 0; i < this.LasMarcas.getSize(); i++) {
                impresoraVO tmoMarca = (impresoraVO) marcas[i];
                this.JCB_marcaimpresora.addItem(tmoMarca);
                if (tmoMarca.getID() == Integer.parseInt(buscado.getMarca())) {
                    this.JCB_marcaimpresora.setSelectedIndex(i);
                }
            }

            System.out.println("la impresora es el" + buscado.getSerie());
        } else {
            System.err.println("la impresora no esta");

        }


    }//GEN-LAST:event_JT_idBuscarActionPerformed

    private void JT_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_SerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_SerieActionPerformed

    private void JT_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_TipoActionPerformed

    private void JB_ACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ACTIVARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_ACTIVARActionPerformed

    private void JB_REGCAMBIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGCAMBIOSActionPerformed

        if (pp.confirmar("esta seguro de realizar \n los cambios") == 0) {
            String serie = JT_Serie.getText();
        } else {

        }
        String serie = this.JT_Serie.getText();
        String tipo = this.JT_Tipo.getText();
        impresoraVO tmpMar = (impresoraVO) this.JCB_marcaimpresora.getSelectedItem();
        int Marca = tmpMar.getID();

        buscado.setSerie(serie);
        buscado.setTipo(tipo);
        buscado.setMarca("" + Marca);
        this.JT_Serie.setVisible(false);
        this.JT_ID.setVisible(false);
        this.JT_Tipo.setVisible(false);
        this.JCB_marcaimpresora.setVisible(false);
        this.JB_ACTIVAR.setVisible(false);
        this.JB_CANCELAR.setVisible(false);
        this.JB_REGCAMBIOS.setVisible(false);
        
        this.JL_ID.setVisible(true);
        this.JL_Marca.setVisible(true);
        this.JL_Serie.setVisible(true);
        this.JL_TIpo.setVisible(true);


    }//GEN-LAST:event_JB_REGCAMBIOSActionPerformed

    private void JCB_marcaimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_marcaimpresoraActionPerformed
      
        
    }//GEN-LAST:event_JCB_marcaimpresoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ACTIVAR;
    private javax.swing.JButton JB_CANCELAR;
    private javax.swing.JButton JB_REGCAMBIOS;
    private javax.swing.JComboBox<impresoraVO> JCB_marcaimpresora;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_Marca;
    private javax.swing.JLabel JL_Serie;
    private javax.swing.JLabel JL_TIpo;
    private javax.swing.JLabel JL_TituloBuscaMoni;
    private javax.swing.JTextField JT_BUScpu;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_Serie;
    private javax.swing.JTextField JT_Tipo;
    private javax.swing.JButton JT_idBuscar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
