/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMonitor;

import DAO.cpuDAO;
import DAO.MarcaDAO;
import Tabla.TablaSimple;
import javax.swing.table.TableModel;


/**
 *
 * @author Sergio
 */
public class ListarcpuUI extends javax.swing.JPanel {

    private cpuDAO Lascpu;
    private MarcaDAO LasMarcas;

    /**
     * Creates new form ListarMoniUI
     */
    public ListarcpuUI(cpuDAO local, MarcaDAO LasMarcas) {

        this.Lascpu = local;
        this.LasMarcas = LasMarcas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_TituloListacpu = new javax.swing.JLabel();
        JB_CargarListacpu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 0));

        JL_TituloListacpu.setBackground(new java.awt.Color(0, 255, 255));
        JL_TituloListacpu.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        JL_TituloListacpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_TituloListacpu.setText("Formulario para listar CPU");

        JB_CargarListacpu.setText("Cargar Lista");
        JB_CargarListacpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CargarListacpuActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(JB_CargarListacpu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JL_TituloListacpu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JL_TituloListacpu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(JB_CargarListacpu))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CargarListacpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CargarListacpuActionPerformed

        
        this.jTable1.setModel(this.Lascpu.crearTabla(LasMarcas));
        
        
        
     //   this.JTA_ListaMoni.setText(this.LosMoni.listaMonitor(this.LasMarcas));

    }//GEN-LAST:event_JB_CargarListacpuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CargarListacpu;
    private javax.swing.JLabel JL_TituloListacpu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
